"""
run_zone_pipeline.py
====================
Single entry point to run the complete zone detection pipeline.

Steps executed in order:
    1. Load processed OHLCV data from data/processed/
    2. Detect swing high/low zones  (swing_zones.py)
    3. Merge overlapping zones       (zone_merger.py)
    4. Score each zone by strength   (zone_scorer.py)
    5. Save final zones to           data/zones/<SYMBOL>_swing_zones.csv

All parameters are read from config/zone_config.yaml.
Change zone behaviour there — do not edit this file.

Usage:
    # Run dev symbols (default)
    python run_zone_pipeline.py

    # Run all Nifty 50 symbols
    python run_zone_pipeline.py --mode full

    # Run specific symbols
    python run_zone_pipeline.py --symbols RELIANCE.NS TCS.NS

    # Skip scoring (faster, just detect and merge)
    python run_zone_pipeline.py --skip-scoring

    # Use a different lookback than zone_config.yaml
    python run_zone_pipeline.py --lookback 10
"""

import sys
import argparse
import logging
from pathlib import Path
from datetime import datetime

import yaml
import pandas as pd

PROJECT_ROOT = Path(__file__).resolve().parent
sys.path.insert(0, str(PROJECT_ROOT))

from src.data.data_loader   import DataLoader
from src.zones              import ZoneConfig, detect_swing_zones, merge_zones, score_zones, save_zones, zone_summary


# ─────────────────────────────────────────────────────────────
# Setup
# ─────────────────────────────────────────────────────────────

def load_main_config() -> dict:
    with open(PROJECT_ROOT / "config" / "config.yaml") as f:
        return yaml.safe_load(f)


def setup_logging(main_cfg: dict) -> logging.Logger:
    log_dir = PROJECT_ROOT / main_cfg["logging"]["log_dir"]
    log_dir.mkdir(parents=True, exist_ok=True)
    log_level = getattr(logging, main_cfg["logging"]["log_level"].upper(), logging.INFO)

    handlers = [logging.StreamHandler()]
    if main_cfg["logging"]["log_to_file"]:
        log_file = log_dir / f"zone_pipeline_{datetime.now().strftime('%Y%m%d_%H%M%S')}.log"
        handlers.append(logging.FileHandler(log_file))

    logging.basicConfig(
        level=log_level,
        format="%(asctime)s | %(levelname)-8s | %(message)s",
        datefmt="%Y-%m-%d %H:%M:%S",
        handlers=handlers,
    )
    return logging.getLogger("zone_pipeline")


# ─────────────────────────────────────────────────────────────
# Per-symbol pipeline
# ─────────────────────────────────────────────────────────────

def run_symbol(
    symbol: str,
    df: pd.DataFrame,
    zone_cfg: ZoneConfig,
    zones_dir: Path,
    lookback_override: int | None,
    skip_scoring: bool,
    logger: logging.Logger,
) -> dict:
    """
    Run the full zone pipeline for one symbol.
    Returns a summary dict for the final report.
    """
    logger.info(f"[{symbol}] Starting zone detection...")

    # ── Step 1: Detect raw swing zones ───────────────────────
    lookback = lookback_override if lookback_override is not None else zone_cfg.swing.lookback
    zones_raw = detect_swing_zones(df, symbol, lookback=lookback, cfg=zone_cfg)

    if zones_raw.empty:
        logger.warning(f"[{symbol}] No zones detected. Skipping.")
        return {"symbol": symbol, "status": "no_zones", "raw": 0, "merged": 0, "scored": 0}

    logger.info(f"[{symbol}] Raw zones: {len(zones_raw)} "
                f"(support={( zones_raw['zone_type']=='support').sum()}, "
                f"resistance={(zones_raw['zone_type']=='resistance').sum()})")

    # ── Step 2: Merge overlapping zones ──────────────────────
    zones_merged = merge_zones(zones_raw, cfg=zone_cfg)
    logger.info(f"[{symbol}] After merging: {len(zones_merged)} zones "
                f"({len(zones_raw) - len(zones_merged)} merged)")

    # ── Step 3: Score zones ───────────────────────────────────
    if not skip_scoring:
        zones_final = score_zones(zones_merged, df, cfg=zone_cfg)
        avg_strength = zones_final["zone_strength"].mean()
        logger.info(f"[{symbol}] After scoring: {len(zones_final)} zones | "
                    f"avg strength={avg_strength:.3f}")
    else:
        zones_final = zones_merged
        avg_strength = None
        logger.info(f"[{symbol}] Scoring skipped (--skip-scoring flag).")

    # ── Step 4: Save zones ────────────────────────────────────
    saved_path = save_zones(zones_final, symbol, zones_dir)
    logger.info(f"[{symbol}] Saved → {saved_path.relative_to(PROJECT_ROOT)}")

    return {
        "symbol"      : symbol,
        "status"      : "success",
        "candles"     : len(df),
        "raw"         : len(zones_raw),
        "merged"      : len(zones_merged),
        "scored"      : len(zones_final),
        "avg_strength": round(avg_strength, 3) if avg_strength is not None else "skipped",
        "saved_to"    : str(saved_path.relative_to(PROJECT_ROOT)),
    }


# ─────────────────────────────────────────────────────────────
# Main
# ─────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(description="ZoneTrend — Zone Detection Pipeline")
    parser.add_argument(
        "--mode", choices=["dev", "full"], default="dev",
        help="'dev' = 9 symbols. 'full' = all Nifty 50.",
    )
    parser.add_argument(
        "--symbols", nargs="+", default=None,
        help="Override: specific symbols e.g. RELIANCE.NS TCS.NS",
    )
    parser.add_argument(
        "--lookback", type=int, default=None,
        help="Override zone_config.yaml swing.lookback for this run.",
    )
    parser.add_argument(
        "--skip-scoring", action="store_true",
        help="Skip zone scoring step (faster). Zones will not have strength scores.",
    )
    args = parser.parse_args()

    # ── Load configs ──────────────────────────────────────────
    main_cfg = load_main_config()
    zone_cfg = ZoneConfig()
    logger   = setup_logging(main_cfg)

    # ── Determine symbols ─────────────────────────────────────
    if args.symbols:
        symbols = args.symbols
        label   = "custom"
    elif args.mode == "dev":
        symbols = main_cfg["data"]["dev_symbols"]
        label   = "dev"
    else:
        symbols = main_cfg["data"]["symbols"]
        label   = "full"

    zones_dir = PROJECT_ROOT / main_cfg["data"]["zones_dir"]
    zones_dir.mkdir(parents=True, exist_ok=True)

    # ── Print run header ──────────────────────────────────────
    logger.info("=" * 60)
    logger.info("ZoneTrend — Zone Detection Pipeline")
    logger.info("=" * 60)
    logger.info(f"Mode             : {label}")
    logger.info(f"Symbols          : {len(symbols)}")
    logger.info(f"Lookback (N)     : {args.lookback if args.lookback else zone_cfg.swing.lookback} "
                f"{'(override)' if args.lookback else '(from zone_config.yaml)'}")
    logger.info(f"Merge dist       : {zone_cfg.merger.merge_distance_atr} ATR")
    logger.info(f"Scoring          : {'disabled' if args.skip_scoring else 'enabled'}")
    logger.info(f"Output dir       : {zones_dir.relative_to(PROJECT_ROOT)}/")
    logger.info("=" * 60)

    # ── Load processed data ───────────────────────────────────
    loader    = DataLoader(source="processed")
    all_data  = loader.load_all(symbols=symbols)

    missing = [s for s in symbols if s not in all_data]
    if missing:
        logger.warning(f"Missing processed data for: {missing}")
        logger.warning("Run: python run_data_pipeline.py first.")

    if not all_data:
        logger.error("No data loaded. Exiting.")
        sys.exit(1)

    # ── Run pipeline per symbol ───────────────────────────────
    total    = len(all_data)
    results  = []
    success  = 0
    failed   = []

    for i, (symbol, df) in enumerate(all_data.items(), 1):
        logger.info(f"[{i}/{total}] {symbol}")
        try:
            result = run_symbol(
                symbol, df, zone_cfg, zones_dir,
                args.lookback, args.skip_scoring, logger
            )
            results.append(result)
            if result["status"] == "success":
                success += 1
            else:
                failed.append(symbol)
        except Exception as e:
            logger.error(f"[{symbol}] Pipeline failed: {e}")
            failed.append(symbol)
            results.append({"symbol": symbol, "status": "error", "error": str(e)})

    # ── Save run summary ──────────────────────────────────────
    summary_df   = pd.DataFrame(results)
    summary_path = zones_dir / "zone_pipeline_summary.csv"
    summary_df.to_csv(summary_path, index=False)

    # ── Print final report ────────────────────────────────────
    logger.info("=" * 60)
    logger.info("ZONE PIPELINE COMPLETE")
    logger.info("=" * 60)
    logger.info(f"Symbols processed : {success}/{total}")
    if failed:
        logger.warning(f"Failed            : {failed}")

    print()
    print("=" * 60)
    print("ZONE PIPELINE SUMMARY")
    print("=" * 60)
    print(f"{'Symbol':<20} {'Candles':>8} {'Raw':>6} {'Merged':>8} {'Final':>7} {'Avg Strength':>13}")
    print("-" * 60)
    for r in results:
        if r["status"] == "success":
            print(f"{r['symbol']:<20} {r['candles']:>8} {r['raw']:>6} {r['merged']:>8} "
                  f"{r['scored']:>7} {str(r['avg_strength']):>13}")
        else:
            print(f"{r['symbol']:<20} {'—':>8} {'—':>6} {'—':>8} {'—':>7} {r['status']:>13}")

    print("=" * 60)
    print(f"\nZone files saved in : {zones_dir.relative_to(PROJECT_ROOT)}/")
    print(f"Run summary saved   : {summary_path.relative_to(PROJECT_ROOT)}")
    print()
    print("Next step:")
    print("  jupyter notebook notebooks/02_zone_detection_analysis.ipynb")


if __name__ == "__main__":
    main()
